---
- name: Template config.php
  template:
    src: 'config.php.j2'
    dest: '{{ limesurvey_path }}/application/config/config.php'
    owner: '{{ limesurvey_user }}'
    group: '{{ limesurvey_group }}'
  notify:
    - limesurvey install
    - clear limesurvey cache
